name: "PTerm Automatic Releases"
description: "Creates a new git tag when the version in cmd/root.go changed."
author: "MarvinJWendt"
branding:
  icon: award
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
